export const lazyTokenVars = {
  color: {
    source: "--ld-color-source",
    primary: "--ld-color-primary",
    onPrimary: "--ld-color-on-primary",
    primaryContainer: "--ld-color-primary-container",
    onPrimaryContainer: "--ld-color-on-primary-container",
    secondary: "--ld-color-secondary",
    onSecondary: "--ld-color-on-secondary",
    secondaryContainer: "--ld-color-secondary-container",
    onSecondaryContainer: "--ld-color-on-secondary-container",
    tertiary: "--ld-color-tertiary",
    onTertiary: "--ld-color-on-tertiary",
    tertiaryContainer: "--ld-color-tertiary-container",
    onTertiaryContainer: "--ld-color-on-tertiary-container",
    background: "--ld-color-background",
    onBackground: "--ld-color-on-background",
    surface: "--ld-color-surface",
    onSurface: "--ld-color-on-surface",
    surfaceVariant: "--ld-color-surface-variant",
    onSurfaceVariant: "--ld-color-on-surface-variant",
    surfaceContainerLow: "--ld-color-surface-container-low",
    surfaceContainer: "--ld-color-surface-container",
    surfaceContainerHigh: "--ld-color-surface-container-high",
    outline: "--ld-color-outline",
    outlineVariant: "--ld-color-outline-variant",
    inverseSurface: "--ld-color-inverse-surface",
    inverseOnSurface: "--ld-color-inverse-on-surface",
    error: "--ld-color-error",
    onError: "--ld-color-on-error",
    focusRing: "--ld-color-focus-ring",
    borderMuted: "--ld-color-border-muted",
    stateHover: "--ld-color-state-hover",
    statePressed: "--ld-color-state-pressed",
    stateSelected: "--ld-color-state-selected",
  },
  shape: {
    cornerExtraSmall: "--ld-shape-corner-extra-small",
    cornerSmall: "--ld-shape-corner-small",
    cornerMedium: "--ld-shape-corner-medium",
    cornerLarge: "--ld-shape-corner-large",
    cornerExtraLarge: "--ld-shape-corner-extra-large",
    cornerFull: "--ld-shape-corner-full",
  },
  motion: {
    durationInstant: "--ld-motion-duration-instant",
    durationFast: "--ld-motion-duration-fast",
    durationNormal: "--ld-motion-duration-normal",
    durationEmphasized: "--ld-motion-duration-emphasized",
    easingStandard: "--ld-motion-easing-standard",
    easingEnter: "--ld-motion-easing-enter",
    easingExit: "--ld-motion-easing-exit",
    easingEmphasized: "--ld-motion-easing-emphasized",
  },
  space: {
    1: "--ld-space-1",
    2: "--ld-space-2",
    3: "--ld-space-3",
    4: "--ld-space-4",
    6: "--ld-space-6",
    8: "--ld-space-8",
    12: "--ld-space-12",
    16: "--ld-space-16",
  },
  typography: {
    display: "--ld-typography-display",
    headingXl: "--ld-typography-heading-xl",
    headingLg: "--ld-typography-heading-lg",
    headingMd: "--ld-typography-heading-md",
    bodyLg: "--ld-typography-body-lg",
    bodyMd: "--ld-typography-body-md",
    bodySm: "--ld-typography-body-sm",
    label: "--ld-typography-label",
    code: "--ld-typography-code",
  },
} as const;

export const lazyCompatibilityVars = {
  color: {
    source: "--ld-source",
    primary: "--ld-primary",
    onPrimary: "--ld-on-primary",
    primaryContainer: "--ld-primary-container",
    onPrimaryContainer: "--ld-on-primary-container",
    secondary: "--ld-secondary",
    onSecondary: "--ld-on-secondary",
    secondaryContainer: "--ld-secondary-container",
    onSecondaryContainer: "--ld-on-secondary-container",
    tertiary: "--ld-tertiary",
    onTertiary: "--ld-on-tertiary",
    tertiaryContainer: "--ld-tertiary-container",
    onTertiaryContainer: "--ld-on-tertiary-container",
    background: "--ld-background",
    onBackground: "--ld-on-background",
    surface: "--ld-surface",
    onSurface: "--ld-on-surface",
    surfaceVariant: "--ld-surface-variant",
    onSurfaceVariant: "--ld-on-surface-variant",
    surfaceContainerLow: "--ld-surface-container-low",
    surfaceContainer: "--ld-surface-container",
    surfaceContainerHigh: "--ld-surface-container-high",
    outline: "--ld-outline",
    outlineVariant: "--ld-outline-variant",
    inverseSurface: "--ld-inverse-surface",
    inverseOnSurface: "--ld-inverse-on-surface",
    error: "--ld-error",
    onError: "--ld-on-error",
    focusRing: "--ld-focus-ring",
    borderMuted: "--ld-border-muted",
    stateHover: "--ld-state-hover",
    statePressed: "--ld-state-pressed",
    stateSelected: "--ld-state-selected",
  },
  shape: {
    cornerExtraSmall: "--ld-radius-xs",
    cornerSmall: "--ld-radius-sm",
    cornerMedium: "--ld-radius-md",
    cornerLarge: "--ld-radius-lg",
    cornerExtraLarge: "--ld-radius-xl",
    cornerFull: "--ld-radius-full",
  },
  motion: {
    durationInstant: "--ld-motion-instant",
    durationFast: "--ld-motion-fast",
    durationNormal: "--ld-motion-normal",
    durationEmphasized: "--ld-motion-emphasized",
    easingStandard: "--ld-ease-standard",
    easingEnter: "--ld-ease-enter",
    easingExit: "--ld-ease-exit",
    easingEmphasized: "--ld-ease-emphasized",
  },
  space: {
    "2xs": "--ld-space-2xs",
    xs: "--ld-space-xs",
    sm: "--ld-space-sm",
    md: "--ld-space-md",
    lg: "--ld-space-lg",
    xl: "--ld-space-xl",
    "2xl": "--ld-space-2xl",
    "3xl": "--ld-space-3xl",
  },
  typography: {
    display: "--ld-type-display",
    headingXl: "--ld-type-heading-xl",
    headingLg: "--ld-type-heading-lg",
    headingMd: "--ld-type-heading-md",
    bodyLg: "--ld-type-body-lg",
    bodyMd: "--ld-type-body-md",
    bodySm: "--ld-type-body-sm",
    label: "--ld-type-label",
    code: "--ld-type-code",
  },
} as const;

export const lazyTokens = {
  color: toRefs(lazyTokenVars.color),
  shape: toRefs(lazyTokenVars.shape),
  motion: toRefs(lazyTokenVars.motion),
  space: toRefs(lazyTokenVars.space),
  typography: toRefs(lazyTokenVars.typography),
} as const;

export type LazyCssVars = Record<string, string>;

export const lazySpaceValues = {
  1: "4px",
  2: "8px",
  3: "12px",
  4: "16px",
  6: "24px",
  8: "32px",
  12: "48px",
  16: "64px",
} as const;

export const lazyTypographyValues = {
  display: "700 40px/48px Inter, ui-sans-serif, system-ui, sans-serif",
  headingXl: "650 28px/36px Inter, ui-sans-serif, system-ui, sans-serif",
  headingLg: "650 22px/30px Inter, ui-sans-serif, system-ui, sans-serif",
  headingMd: "650 18px/26px Inter, ui-sans-serif, system-ui, sans-serif",
  bodyLg: "400 16px/26px Inter, ui-sans-serif, system-ui, sans-serif",
  bodyMd: "400 14px/22px Inter, ui-sans-serif, system-ui, sans-serif",
  bodySm: "400 13px/20px Inter, ui-sans-serif, system-ui, sans-serif",
  label: "650 12px/16px Inter, ui-sans-serif, system-ui, sans-serif",
  code: "500 13px/20px SFMono-Regular, Consolas, Liberation Mono, monospace",
} as const;

export function createFoundationVars(): LazyCssVars {
  const vars: LazyCssVars = {
    [lazyTokenVars.space[1]]: lazySpaceValues[1],
    [lazyTokenVars.space[2]]: lazySpaceValues[2],
    [lazyTokenVars.space[3]]: lazySpaceValues[3],
    [lazyTokenVars.space[4]]: lazySpaceValues[4],
    [lazyTokenVars.space[6]]: lazySpaceValues[6],
    [lazyTokenVars.space[8]]: lazySpaceValues[8],
    [lazyTokenVars.space[12]]: lazySpaceValues[12],
    [lazyTokenVars.space[16]]: lazySpaceValues[16],
    [lazyTokenVars.typography.display]: lazyTypographyValues.display,
    [lazyTokenVars.typography.headingXl]: lazyTypographyValues.headingXl,
    [lazyTokenVars.typography.headingLg]: lazyTypographyValues.headingLg,
    [lazyTokenVars.typography.headingMd]: lazyTypographyValues.headingMd,
    [lazyTokenVars.typography.bodyLg]: lazyTypographyValues.bodyLg,
    [lazyTokenVars.typography.bodyMd]: lazyTypographyValues.bodyMd,
    [lazyTokenVars.typography.bodySm]: lazyTypographyValues.bodySm,
    [lazyTokenVars.typography.label]: lazyTypographyValues.label,
    [lazyTokenVars.typography.code]: lazyTypographyValues.code,
  };

  Object.assign(vars, {
    [lazyCompatibilityVars.space["2xs"]]: vars[lazyTokenVars.space[1]],
    [lazyCompatibilityVars.space.xs]: vars[lazyTokenVars.space[2]],
    [lazyCompatibilityVars.space.sm]: vars[lazyTokenVars.space[3]],
    [lazyCompatibilityVars.space.md]: vars[lazyTokenVars.space[4]],
    [lazyCompatibilityVars.space.lg]: vars[lazyTokenVars.space[6]],
    [lazyCompatibilityVars.space.xl]: vars[lazyTokenVars.space[8]],
    [lazyCompatibilityVars.space["2xl"]]: vars[lazyTokenVars.space[12]],
    [lazyCompatibilityVars.space["3xl"]]: vars[lazyTokenVars.space[16]],
    [lazyCompatibilityVars.typography.display]: vars[lazyTokenVars.typography.display],
    [lazyCompatibilityVars.typography.headingXl]: vars[lazyTokenVars.typography.headingXl],
    [lazyCompatibilityVars.typography.headingLg]: vars[lazyTokenVars.typography.headingLg],
    [lazyCompatibilityVars.typography.headingMd]: vars[lazyTokenVars.typography.headingMd],
    [lazyCompatibilityVars.typography.bodyLg]: vars[lazyTokenVars.typography.bodyLg],
    [lazyCompatibilityVars.typography.bodyMd]: vars[lazyTokenVars.typography.bodyMd],
    [lazyCompatibilityVars.typography.bodySm]: vars[lazyTokenVars.typography.bodySm],
    [lazyCompatibilityVars.typography.label]: vars[lazyTokenVars.typography.label],
    [lazyCompatibilityVars.typography.code]: vars[lazyTokenVars.typography.code],
  });

  return vars;
}

function toRefs<T extends Record<string, string>>(vars: T) {
  return Object.fromEntries(Object.entries(vars).map(([key, value]) => [key, `var(${value})`])) as {
    readonly [Key in keyof T]: `var(${T[Key]})`;
  };
}
